pagopa/idpay-ranking

helm/values.yaml, pom.xml, src/main/java/it/gov/pagopa/ranking/config/RestConnectorConfig.java, src/main/java/it/gov/pagopa/ranking/connector/rest/pdv/PdvErrorDecoder.java, src/main/java/it/gov/pagopa/ranking/connector/rest/pdv/UserRestClient.java, src/main/java/it/gov/pagopa/ranking/connector/rest/pdv/UserRestService.java, src/main/java/it/gov/pagopa/ranking/connector/rest/pdv/UserRestServiceImpl.java, src/main/java/it/gov/pagopa/ranking/dto/csv/RankingCsvDTO.java, src/main/java/it/gov/pagopa/ranking/dto/mapper/OnboardingRankingRequests2RankingCsvDTOMapper.java, src/main/java/it/gov/pagopa/ranking/dto/pdv/UserInfoPDV.java, src/main/java/it/gov/pagopa/ranking/exception/ErrorManager.java, src/main/java/it/gov/pagopa/ranking/model/User.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/ranking/BaseIntegrationTest.java, src/test/java/it/gov/pagopa/ranking/connector/rest/pdv/PdvErrorDecoderSpy.java, src/test/java/it/gov/pagopa/ranking/connector/rest/pdv/UserRestServiceImplIntegrationTest.java, src/test/java/it/gov/pagopa/ranking/connector/rest/pdv/UserRestServiceImplTest.java, src/test/java/it/gov/pagopa/ranking/connector/rest/pdv/UserRestServiceImplTestIntegrated.java, src/test/java/it/gov/pagopa/ranking/dto/mapper/OnboardingRankingRequests2RankingCsvDTOMapperTest.java, src/test/java/it/gov/pagopa/ranking/service/initiative/ranking/OnboardingRankingBuildFileMediatorServiceImplIntegrationTest.java, src/test/resources/stub/pdv/mappings/getUserInfoByUserId.json, src/test/resources/stub/pdv/mappings/getUserInfoByUserIdBadRequest.json, src/test/resources/stub/pdv/mappings/getUserInfoByUserIdHttpForbidden.json, src/test/resources/stub/pdv/mappings/getUserInfoByUserIdInternalServerError.json, src/test/resources/stub/pdv/mappings/getUserInfoByUserIdNotFound.json, src/test/resources/stub/pdv/mappings/getUserInfoByUserIdTooManyRequest.json
=> IREER-225 fiscalCode in CSV

src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java, src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryTestIntegrated.java
* IDP-1106 findById optimize to be run on cosmosDB
* extending coverage
=> feat: IDP-1106 findById optimize to be run on cosmosDB (#68)

src/test/java/it/gov/pagopa/common/kafka/service/ErrorNotifierServiceTest.java, src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
* Testing ErrorNotifierService
* fixed unitTest
=> feat: Testing ErrorNotifierService (#71)

src/main/java/it/gov/pagopa/ranking/service/initiative/InitiativePersistenceMediatorImpl.java
**Description**
The purpose of this PR is to allign performance logs for the initiative delete.
**List of changes**
-  Modify performance log and info log
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**
=> fix: delete initiative fix performance log

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md, .github/workflow/anchore.yml, .github/workflow/pr-title.yml, .github/workflow/release.yml, .releaserc.json, CODEOWNERS, Dockerfile, helm/Chart.lock, helm/Chart.yaml, helm/values.yaml
This PR proposes several devops improvements:
- dependency version pinning
- helm chart upgrade
- new triggers on anchore action
- fix on release action
- new pull request template
- change anchore slack notification template
- add codeowners
=> fix: [IDP-1720] devops improvements on helm, actions and dockerfile

.github/workflows/anchore.yml
=> chore: send notification slack

.grype.yaml, Dockerfile, pom.xml
=> feat: IDP-1750 fixCve

.grype.yaml, Dockerfile, pom.xml
=> feat: IDP-1750 fixCve (#93)

src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeApiRetryable.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java, src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java
IDP-1765 allow mongo RequestRateTooLarge exception always retryable for selected API
=> feat: IDP-1765 selected API retryable

pom.xml, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeApiRetryable.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java, src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java
=> feat: Release dev

Dockerfile, src/main/java/it/gov/pagopa/ranking/constants/OnboardingConstants.java, src/main/java/it/gov/pagopa/ranking/dto/OnboardingRankingRequestDTO.java, src/main/java/it/gov/pagopa/ranking/dto/controller/RankingRequestsApiDTO.java, src/main/java/it/gov/pagopa/ranking/dto/event/EvaluationRankingDTO.java, src/main/java/it/gov/pagopa/ranking/dto/initiative/InitiativeGeneralDTO.java, src/main/java/it/gov/pagopa/ranking/dto/mapper/InitiativeBuild2ConfigMapper.java, src/main/java/it/gov/pagopa/ranking/dto/mapper/OnboardingRankingRequest2RankingRequestsApiDTOMapper.java, src/main/java/it/gov/pagopa/ranking/dto/mapper/OnboardingRankingRequestsDTO2ModelMapper.java, src/main/java/it/gov/pagopa/ranking/model/InitiativeConfig.java, src/main/java/it/gov/pagopa/ranking/model/OnboardingRankingRequests.java, src/main/java/it/gov/pagopa/ranking/service/RankingErrorNotifierService.java, src/main/java/it/gov/pagopa/ranking/service/RankingErrorNotifierServiceImpl.java, src/main/java/it/gov/pagopa/ranking/service/RankingRequestsApiServiceImpl.java, src/main/java/it/gov/pagopa/ranking/service/notify/OnboardingNotifierServiceImpl.java, src/test/java/it/gov/pagopa/ranking/BaseIntegrationTest.java, src/test/java/it/gov/pagopa/ranking/controller/RankingApiControllerImplIntegrationTest.java, src/test/java/it/gov/pagopa/ranking/controller/RankingApiControllerImplTest.java, src/test/java/it/gov/pagopa/ranking/dto/mapper/OnboardingRankingRequest2RankingRequestsApiDTOMapperTest.java, src/test/java/it/gov/pagopa/ranking/dto/mapper/OnboardingRankingRequestsDTO2ModelMapperTest.java, src/test/java/it/gov/pagopa/ranking/event/InitiativeConsumerConfigTest.java, src/test/java/it/gov/pagopa/ranking/service/notify/OnboardingNotifierServiceImplTest.java, src/test/java/it/gov/pagopa/ranking/test/fakers/Initiative2BuildDTOFaker.java, src/test/java/it/gov/pagopa/ranking/test/fakers/InitiativeConfigFaker.java, src/test/java/it/gov/pagopa/ranking/test/fakers/OnboardingRankingRequestsDTOFaker.java
Feature for ranking on initiative with family unit.
- Flow for initiative ranking type with family unit.
- Update Ranking request API for new field familyId. 
=> feat: Idp 1743 sviluppo be

src/main/java/it/gov/pagopa/ranking/dto/event/EvaluationRankingDTO.java, src/main/java/it/gov/pagopa/ranking/dto/mapper/OnboardingRankingRequest2EvaluationMapper.java
This pr is related to a fix for task [IDP-1743](https://pagopa.atlassian.net/browse/IDP-1743)
- added familyId in onboarding outcome
[IDP-1743]: https://pagopa.atlassian.net/browse/IDP-1743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [IDP-1743] fix notify family field

Dockerfile, pom.xml, src/main/java/it/gov/pagopa/ranking/constants/OnboardingConstants.java, src/main/java/it/gov/pagopa/ranking/dto/OnboardingRankingRequestDTO.java, src/main/java/it/gov/pagopa/ranking/dto/controller/RankingRequestsApiDTO.java, src/main/java/it/gov/pagopa/ranking/dto/event/EvaluationRankingDTO.java, src/main/java/it/gov/pagopa/ranking/dto/initiative/InitiativeGeneralDTO.java, src/main/java/it/gov/pagopa/ranking/dto/mapper/InitiativeBuild2ConfigMapper.java, src/main/java/it/gov/pagopa/ranking/dto/mapper/OnboardingRankingRequest2RankingRequestsApiDTOMapper.java, src/main/java/it/gov/pagopa/ranking/dto/mapper/OnboardingRankingRequestsDTO2ModelMapper.java, src/main/java/it/gov/pagopa/ranking/model/InitiativeConfig.java, src/main/java/it/gov/pagopa/ranking/model/OnboardingRankingRequests.java, src/main/java/it/gov/pagopa/ranking/service/RankingErrorNotifierService.java, src/main/java/it/gov/pagopa/ranking/service/RankingErrorNotifierServiceImpl.java, src/main/java/it/gov/pagopa/ranking/service/RankingRequestsApiServiceImpl.java, src/main/java/it/gov/pagopa/ranking/service/notify/OnboardingNotifierServiceImpl.java, src/test/java/it/gov/pagopa/ranking/BaseIntegrationTest.java, src/test/java/it/gov/pagopa/ranking/controller/RankingApiControllerImplIntegrationTest.java, src/test/java/it/gov/pagopa/ranking/controller/RankingApiControllerImplTest.java, src/test/java/it/gov/pagopa/ranking/dto/mapper/OnboardingRankingRequest2RankingRequestsApiDTOMapperTest.java, src/test/java/it/gov/pagopa/ranking/dto/mapper/OnboardingRankingRequestsDTO2ModelMapperTest.java, src/test/java/it/gov/pagopa/ranking/event/InitiativeConsumerConfigTest.java, src/test/java/it/gov/pagopa/ranking/service/notify/OnboardingNotifierServiceImplTest.java, src/test/java/it/gov/pagopa/ranking/test/fakers/Initiative2BuildDTOFaker.java, src/test/java/it/gov/pagopa/ranking/test/fakers/InitiativeConfigFaker.java, src/test/java/it/gov/pagopa/ranking/test/fakers/OnboardingRankingRequestsDTOFaker.java
Promotion to UAT
- Task [IDP-1743](https://pagopa.atlassian.net/browse/IDP-1743) -> [PR](https://github.com/pagopa/idpay-ranking/pull/92)
[IDP-1743]: https://pagopa.atlassian.net/browse/IDP-1743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: promote to UAT

src/main/java/it/gov/pagopa/ranking/service/notify/OnboardingNotifierServiceImpl.java, src/test/java/it/gov/pagopa/ranking/controller/RankingApiControllerImplIntegrationTest.java
The purpose of this PR is to fix the management of onboarding when the user status is eligible_ko
- add to onboarding queue the event related to eligible_ko families
=> fix: inviteFamilyMembers when status is eligible_ko

pom.xml, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java, src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java, src/main/java/it/gov/pagopa/common/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java, src/main/java/it/gov/pagopa/ranking/controller/RankingApiControllerImpl.java, src/test/java/it/gov/pagopa/common/mongo/DummySpringRepository.java, src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java, src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java, src/test/java/it/gov/pagopa/ranking/event/InitiativeConsumerConfigTest.java
=> fix: Idp 2003 fix mongo retry when anonymous repo

.grype.yaml, Dockerfile, pom.xml, src/main/java/it/gov/pagopa/common/stream/StreamsHealthIndicator.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/main/resources/application.yml, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
=> fix: Idp 2016 fix CVE

.github/CODEOWNERS, Dockerfile, src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java, src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestSyncClient.java, src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java, src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java, src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryTestIntegrated.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java, src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java, src/test/java/it/gov/pagopa/ranking/BaseIntegrationTest.java, src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports, src/test/resources/mongodbEmbeddedDisabled.properties
=> chore: Release dev

src/main/java/it/gov/pagopa/ranking/service/notify/OnboardingNotifierServiceImpl.java, src/test/java/it/gov/pagopa/ranking/controller/RankingApiControllerImplIntegrationTest.java
=> fix: update rejection reason

pom.xml, src/main/java/it/gov/pagopa/ranking/constants/OnboardingConstants.java, src/main/java/it/gov/pagopa/ranking/dto/event/OnboardingRejectionReason.java, src/main/java/it/gov/pagopa/ranking/service/notify/OnboardingNotifierServiceImpl.java, src/test/java/it/gov/pagopa/ranking/controller/RankingApiControllerImplIntegrationTest.java
- Fix Rejections reason for family members ELEGIBLE_KO [PR](https://github.com/pagopa/idpay-ranking/commit/67f0bfd0911b9dbdd36bb696692219f6b1f90c42)
=> feat: Promote UAT

src/main/java/it/gov/pagopa/ranking/service/RankingRequestsApiServiceImpl.java, src/test/java/it/gov/pagopa/ranking/service/RankingRequestsApiServiceImplTest.java
The purpose of this PR is to manage ranking publication when ranking is already published.
Task [IDP-1811](https://pagopa.atlassian.net/browse/IDP-1811)
- remove exception when ranking status is COMPLETED
[IDP-1811]: https://pagopa.atlassian.net/browse/IDP-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: [IDP-1811] fix ranking publication when status is COMPLETED

.grype.yaml, Dockerfile, pom.xml, src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java, src/test/java/it/gov/pagopa/ranking/BaseIntegrationTest.java, src/test/java/it/gov/pagopa/ranking/controller/RankingApiControllerImplIntegrationTest.java, src/test/java/it/gov/pagopa/ranking/service/sign/P7mSignerServiceTest.java
=> fix: IDP-2196 fix Cve

src/main/java/it/gov/pagopa/common/web/dto/ErrorDTO.java, src/main/java/it/gov/pagopa/common/web/exception/ErrorManager.java, src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceException.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceExceptionHandler.java, src/main/java/it/gov/pagopa/common/web/exception/ServiceExceptionPayload.java, src/main/java/it/gov/pagopa/common/web/exception/ValidationExceptionHandler.java, src/main/java/it/gov/pagopa/ranking/config/RankingErrorManagerConfig.java, src/main/java/it/gov/pagopa/ranking/config/ServiceExceptionConfig.java, src/main/java/it/gov/pagopa/ranking/constants/RankingConstants.java, src/main/java/it/gov/pagopa/ranking/dto/mapper/OnboardingRankingRequest2EvaluationMapper.java, src/main/java/it/gov/pagopa/ranking/exception/InitiativeNotFoundException.java, src/main/java/it/gov/pagopa/ranking/exception/InitiativeNotRelatedException.java, src/main/java/it/gov/pagopa/ranking/service/RankingContextHolderServiceImpl.java, src/main/java/it/gov/pagopa/ranking/service/initiative/InitiativeConfigServiceImpl.java, src/main/java/it/gov/pagopa/ranking/service/notify/OnboardingNotifierServiceImpl.java, src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java, src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java, src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java, src/test/java/it/gov/pagopa/common/web/exception/ServiceExceptionHandlerTest.java, src/test/java/it/gov/pagopa/common/web/exception/ValidationExceptionHandlerTest.java, src/test/java/it/gov/pagopa/ranking/controller/RankingApiControllerImplIntegrationTest.java, src/test/java/it/gov/pagopa/ranking/controller/RankingApiControllerImplTest.java, src/test/java/it/gov/pagopa/ranking/controller/RankingControllerTest.java, src/test/java/it/gov/pagopa/ranking/service/RankingContextHolderServiceImplTest.java, src/test/java/it/gov/pagopa/ranking/service/initiative/InitiativeConfigServiceImplTest.java, src/test/java/it/gov/pagopa/ranking/service/sign/P7mSignerServiceTest.java
The purpose of this pr is to change the way exceptions are handled adding custom exception classes
- Added custom exception classes, exception codes and messages
- Modified ErrorDTO
- Modified MongoExceptionHandler and ValidationExceptionHandler exception codes
- Modified JUnit tests
=> feat: IDP-2235 new errors codes

specs/asyncapi.yml
=> chore: [IDP-2491] add async documentation

src/main/resources/logback-spring.xml
- Update logback configuration to prevent log injection [PR](https://github.com/pagopa/idpay-ranking/pull/145)
=> fix: [IDP-2530] add github action (#145)

pom.xml, src/main/resources/logback-spring.xml
- Update logback configuration
=> fix: [IDP-2530] update logback configuration

pom.xml, src/main/resources/logback-spring.xml
- Update logback configuration [PR](https://github.com/pagopa/idpay-ranking/pull/148)
- [] Unit
=> fix: promote tu UAT

pom.xml, src/main/resources/logback-spring.xml
- Revert logback configuration 
=> fix: promote to UAT

.grype.yaml, Dockerfile, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, helm/values.yaml, pom.xml, src/main/java/it/gov/pagopa/ranking/connector/rest/pdv/PdvErrorDecoder.java, src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java, src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java
- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV, UAT, PROD
[PR](https://github.com/pagopa/idpay-ranking/pull/156)
=> chore: Promote to Uat

.grype.yaml, Dockerfile, helm/values-dev.yaml, helm/values-prod.yaml, helm/values-uat.yaml, helm/values.yaml, pom.xml, src/main/java/it/gov/pagopa/ranking/connector/rest/pdv/PdvErrorDecoder.java, src/main/resources/logback-spring.xml, src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java, src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java
- Fix CVE [PR](https://github.com/pagopa/idpay-ranking/pull/157)
- Fix helm values UAT [PR](https://github.com/pagopa/idpay-ranking/pull/158)
=> chore: promote to MAIN

Dockerfile
=> chore: fix cve (#164)

.github/CODEOWNERS, Dockerfile, pom.xml
=> fix cve (#167)
